# basic config
suffix: Default
device: 0
dataset: mnist
model: mlp

# federated config
total_num: 5
sr: 0.3
rnd: 10
test_gap: 1
stopwatch_mode: real
client_speed: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

# local training config
bs: 10
epoch: 3
lr: 0.1
gamma: 0.99

